/**
 * MSG91 SMS OTP provider — fallback channel.
 *
 * MSG91 is the SMS path; users who can't or won't receive WhatsApp
 * land here. Sender ID is `NXGNCN` (DLT-registered). Template ID is
 * pre-approved per DLT-Sahyog. The SMS body is server-side rendered
 * by MSG91 from the template + OTP variable.
 *
 * Mock mode: when MSG91_AUTH_KEY is unset, returns
 * { ok: true, mock: true, channel: "sms" } without hitting MSG91.
 *
 * v16 web pivot §P0. Replaces the historical web/src/lib/msg91.ts
 * which lived in the wrong workspace and was never wired into the
 * tRPC OTP send path.
 */
import type { OtpProvider, SendOtpInput, SendOtpResult } from "./types";

const MSG91_SEND_URL = "https://control.msg91.com/api/v5/otp";
const FETCH_TIMEOUT_MS = 10_000;
const MAX_RETRIES = 1;

function phoneTag(phoneE164: string): string {
  if (phoneE164.length < 6) return "***";
  return `${phoneE164.slice(0, 3)}***${phoneE164.slice(-2)}`;
}

let mockWarned = false;
function isMock(): boolean {
  if (process.env.MOCK_OTP === "true") return true;
  const inProd =
    process.env.NODE_ENV === "production" || process.env.VERCEL_ENV === "production";
  if (inProd) return false;
  if (!process.env.MSG91_AUTH_KEY || !process.env.MSG91_TEMPLATE_ID) {
    if (!mockWarned) {
      mockWarned = true;
      console.warn(
        "[msg91-sms] no MSG91 credentials configured — falling back to mock send. " +
          "Set MSG91_AUTH_KEY + MSG91_TEMPLATE_ID to send via MSG91.",
      );
    }
    return true;
  }
  return false;
}

type MsgResponse = {
  type?: "success" | "error";
  message?: string;
  request_id?: string;
};

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

async function fetchWithRetry(url: string, init: RequestInit): Promise<Response> {
  let lastErr: unknown;
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(url, { ...init, signal: controller.signal });
      clearTimeout(timer);
      // 5xx is retryable; 4xx is not (rate-limit / auth — retry would burn budget)
      if (res.status >= 500 && attempt < MAX_RETRIES) {
        lastErr = new Error(`MSG91 5xx: ${res.status}`);
        await sleep(300 + Math.floor(Math.random() * 300));
        continue;
      }
      return res;
    } catch (err) {
      clearTimeout(timer);
      lastErr = err;
      if (attempt < MAX_RETRIES) {
        await sleep(300 + Math.floor(Math.random() * 300));
        continue;
      }
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error("MSG91 fetch failed");
}

export const msg91SmsProvider: OtpProvider = {
  channel: "sms",
  async send({ phoneE164, code }: SendOtpInput): Promise<SendOtpResult> {
    if (isMock()) {
      // The mock-mode OTP code is whatever the caller passed — the mock
      // doesn't deliver a message, just acknowledges receipt. The
      // tRPC procedure persists the same code for the verify step,
      // so dev OTPs are deterministic per session.
      console.log(`[mock-msg91] OTP ${code} → ${phoneTag(phoneE164)}`);
      return { ok: true, channel: "sms", mock: true };
    }

    const authKey = process.env.MSG91_AUTH_KEY;
    const templateId = process.env.MSG91_TEMPLATE_ID;
    const senderId = process.env.MSG91_SENDER_ID ?? "NXGNCN";

    if (!authKey || !templateId) {
      console.error("[msg91-sms] missing MSG91 env in production");
      return {
        ok: false,
        channel: "sms",
        error: "E016:sms_not_configured",
        retryable: false,
      };
    }

    // MSG91 wants bare digits with country code, no leading "+".
    const mobile = phoneE164.replace(/^\+/, "");

    // Note: the OTP value is generated by MSG91 server-side based on
    // the template_id config. We pass the `otp` query param to bind
    // OUR generated code (so the verify path can match it). MSG91's
    // verify endpoint accepts our value when sent this way.
    const url =
      `${MSG91_SEND_URL}?template_id=${encodeURIComponent(templateId)}` +
      `&mobile=${encodeURIComponent(mobile)}` +
      `&sender=${encodeURIComponent(senderId)}` +
      `&otp=${encodeURIComponent(code)}`;

    try {
      const res = await fetchWithRetry(url, {
        method: "POST",
        headers: {
          authkey: authKey,
          "Content-Type": "application/json",
          accept: "application/json",
        },
        body: "{}",
      });

      const body = (await res.json().catch(() => ({}))) as MsgResponse;
      if (body.type === "success") {
        return {
          ok: true,
          channel: "sms",
          mock: false,
          requestId: body.request_id ?? body.message,
        };
      }

      console.error(
        `[msg91-sms] ${phoneTag(phoneE164)} status=${res.status} message=${body.message ?? "?"}`,
      );

      return {
        ok: false,
        channel: "sms",
        error: "E017:sms_send_failed",
        retryable: res.status >= 500,
      };
    } catch (err) {
      console.error(
        `[msg91-sms] ${phoneTag(phoneE164)} threw:`,
        err instanceof Error ? err.message : err,
      );
      return {
        ok: false,
        channel: "sms",
        error: "E018:sms_timeout",
        retryable: true,
      };
    }
  },
};
